microservices_chatbot/frontend/api/base/forms.py
import quart.flask_patch
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Optional
from flask_wtf.file import FileAllowed, FileRequired, FileField


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Log In")


class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), EqualTo("pass_confirm", message="Must match")])
    pass_confirm = PasswordField("Confirm Password", validators=[DataRequired()])
    submit = SubmitField("Register")


class UpdateForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[Email(), DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    picture = FileField("Update profile picture", validators=[Optional(), FileAllowed(["jpg", "png", "jpeg"])])
    update = SubmitField("Update")
    delete = SubmitField("Delete")

microservices_chatbot/frontend/api/chat/forms.py
import quart.flask_patch
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class ChatForm(FlaskForm):
    text = StringField('Enter text', validators=[DataRequired()])
    send = SubmitField("Send")

microservices_chatbot/frontend/api/base/__init__.py
CREATE_USER_COMMAND = """
mutation CreateUser($input: CreateUserInput) {
  user: CreateUser(input: $input) {
    id
    username
    email
    password_hash
    date
  }
}
"""
LOGIN_USER_COMMAND = """
{
  login(email:"EMAIL", 
    password:"PASSWORD"){
    id
    username
    picture
  } 
}
"""
UPDATE_USER_COMMAND = """
mutation UpdateUser($input: UpdateUserInput) {
  update: UpdateUser(input: $input) {
    id
    username
    email
    password_hash
    date
    picture
  }
}
"""
DELETE_USER_COMMAND = """
{
  delete(id: "ID"){
    id
    username
  }
}
"""

microservices_chatbot/frontend/api/base/views.py
import os
from random import randint

import requests
from quart import Blueprint, render_template, redirect, url_for, request
from flask_login import login_user, UserMixin, logout_user, login_required, current_user
from werkzeug.utils import secure_filename
from PIL import Image

from frontend.api import url_for_chat, content_headers, save_user, get_user, get_logs, post_request
from frontend.api.measure.views import measure_endpoint
from frontend.api.base.forms import LoginForm, RegisterForm, UpdateForm
from frontend.api.chat.views import clear_chat
from frontend.api.base import (
    CREATE_USER_COMMAND,
    LOGIN_USER_COMMAND,
    UPDATE_USER_COMMAND,
    DELETE_USER_COMMAND
)

core = Blueprint("core", __name__)


async def save_picture(f):
    filename = secure_filename(f.filename)
    base = os.path.abspath(os.path.dirname(__name__))
    folder = os.path.join(base, "frontend", "static", "images")
    path = os.path.join(folder, filename)
    await f.save(path)
    picture = Image.open(path)
    os.remove(path)
    picture.thumbnail((50, 50))
    [os.remove(os.path.join(folder, i)) for i in os.listdir(folder) if i.startswith(get_user().get('username'))]
    picture_name = f"{get_user().get('username')}_{randint(0, 1000)}.png"
    picture_path = os.path.join(folder, picture_name)
    picture.save(picture_path)
    return picture_name


class User(UserMixin):
    def __repr__(self):
        return f"<User {self.__dict__}"


@core.route("/")
@measure_endpoint
async def home():
    return await render_template("index.html", page="home")


@core.route("/login", methods=["POST", "GET"])
@measure_endpoint
async def login():
    form = LoginForm()
    if form.validate_on_submit():
        query = LOGIN_USER_COMMAND.replace(
            "EMAIL", form.data["email"]).replace(
            "PASSWORD", form.data["password"])

        response = post_request(query=query)
        user = response.json().get('data').get('login')
        if user:
            user_login = User()
            user_login.id = user.get("id")
            login_user(user_login)
            save_user(user)
            return redirect(url_for("core.home", page="home", current_user=current_user))
    return await render_template("login.html", page="login", form=form)


@core.route("/register", methods=["POST", "GET"])
@measure_endpoint
async def register():
    form = RegisterForm()
    if form.validate_on_submit():
        credentials = {"username": form.data["username"],
                       "email": form.data["email"],
                       "password": form.data["password"]}
        response = post_request(query=CREATE_USER_COMMAND, input=credentials)
        if response.json().get('data').get('user'):
            return redirect(url_for("core.login"))
    return await render_template("register.html", page="register", form=form)


@core.route("/account", methods=["POST", "GET"])
@login_required
@measure_endpoint
async def account():
    form = UpdateForm()

    if request.method == "POST":
        if form.data.get("update"):
            f = form.picture.data
            response = post_request(
                query=UPDATE_USER_COMMAND,
                input=dict(
                    id=current_user.id,
                    email=form.data.get('email'),
                    new_username=form.data.get('username'),
                    password=form.data.get('password'),
                    picture=await save_picture(f)if f else None
                )

            )
            user = response.json().get('data').get('update')
            if user:
                save_user(user)

        elif form.data.get("delete"):
            query = DELETE_USER_COMMAND.replace("ID", current_user.id)
            response = post_request(query=query)
            return redirect(url_for("core.logout"))

    return await render_template("account.html", page="account", form=form, user=get_user())


@core.route("/logout", methods=["GET"])
@login_required
@measure_endpoint
async def logout():
    get_logs(reset=True)
    clear_chat()
    logout_user()
    return redirect(url_for("core.home", page="home"))

microservices_chatbot/frontend/api/chat/__init__.py
CREATE_POST_COMMAND = """
mutation CreatePost($input: CreatePostInput) {
  post: CreatePost(input: $input) {
    user_id
  }
}
"""

microservices_chatbot/frontend/api/chat/views.py
from datetime import datetime

import requests
from quart import Blueprint, render_template, redirect, url_for

from frontend.api import get_user
from frontend.api.measure.views import measure_endpoint
from flask_login import login_required, current_user

from frontend.api.chat.forms import ChatForm
from frontend.api import url_for_ai, post_request
from frontend.api.chat import CREATE_POST_COMMAND

chats = Blueprint("chats", __name__)

responses = []


def clear_chat():
    global responses
    responses.clear()
    responses = []


@chats.route("/chat", methods=["POST", "GET"])
@login_required
@measure_endpoint
async def chat():
    global responses
    form = ChatForm()
    if form.validate_on_submit():
        reset_memory = 10 if len(responses) % 10 == 0 else 0
        user_text = form.data.get("text")
        user_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        response = requests.request(
            method="POST",
            url=f"{url_for_ai}/chat",
            json={
                "input": user_text,
                "input_date": user_date,
                "reset": reset_memory,
            }
        )
        response = response.json()
        responses.append(response)

        response = post_request(
            query=CREATE_POST_COMMAND,
            input=dict(
                user_id=current_user.id,
                user_text=user_text,
                user_date=user_date,
                ai_text=response.get('output'),
                ai_date=response.get('output_date')

            )

        )

        return redirect(url_for('chats.chat'))
    return await render_template("chat.html", page="chat", form=form, data=responses, user=get_user())


@chats.route("/reset", methods=['POST', "GET"])
async def reset():
    global responses
    responses.clear()
    return redirect(url_for('chats.chat'))

microservices_chatbot/frontend/api/measure/views.py
import time
import datetime
from functools import wraps

from quart import Blueprint, render_template, request
from flask_login import login_required, current_user
from frontend.api.measure import GET_POSTS_BY_USER_ID_COMMAND
from frontend.api import get_logs, post_request

measurements = Blueprint("measurements", __name__)


def counter(num=1, length=3):
    number = '0' * length + str(num)
    number = number[len(number)-length:]
    return number


def results(name):
    try:
        logs = [float(log["took"]) for log in get_logs()["logs"] if log.get("name") == name]
        return f"{min(logs):.3f} | {max(logs):.3f} | {sum(logs) / len(logs):.3f}"
    except ValueError:
        return f"0.000 | 0.000 | 0.000"


def measure_endpoint(f):
    @wraps(f)
    async def decorated_function(*args, **kwargs):
        start = time.time()
        get_logs()['count'] += 1
        c = counter(num=get_logs()["count"], length=6)
        result = await f(*args, **kwargs)
        took = round(time.time() - start, 3)
        date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        get_logs()["logs"].append({"tag": c, "name": f.__name__, "took": took, "date": date, "mean": results(f.__name__)})
        return result
    return decorated_function


@measurements.route("/stats")
@login_required
@measure_endpoint
async def stats():
    logs = get_logs().get("logs")
    logs.reverse()
    logs = logs[:-1 if len(logs) <= 20 else 20]
    return await render_template("stats.html", logs=logs)


@measurements.route("/history")
@login_required
@measure_endpoint
async def history():
    response = post_request(query=GET_POSTS_BY_USER_ID_COMMAND.replace("ID", current_user.id))
    posts = response.json().get('data').get('posts')
    return await render_template("history.html", posts=posts)

microservices_chatbot/frontend/templates/401.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>401</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="static/errors/401.css">
    <!------ Include the above in your HEAD tag ---------->

</head>


<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>
                    401 Unauthorized access !</h2>
                <div class="error-details">
                    Sorry, an error has occurred, you are not logged in!
                </div>
                <div class="error-actions">
                    <a href="{{url_for('core.home')}}" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                        Take Me Home </a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

microservices_chatbot/frontend/templates/account.html
{% extends "base.html" %}
{% block content %}


<style>
	.signup-form{
		width: 400px;
		margin: 0 auto;
	}
    .signup-form form{
		color: #999;
		border-radius: 3px;
    	margin-top: 40px;
    	margin-bottom: 15px;
        background: #f2f3f7;
        padding: 30px;
    }

.form-control{
  height: 45px;
  margin-bottom: 1px;
  border-radius: 0px;
  border: 2px solid gray;
  font-size: 20px;
  color: gray;
}

.custom-file-upload {
    border: 0px;
    font-size: 20px;
    font-weight: bold;
    display: inline-block;
    padding: 7px 13px;
    cursor: pointer;
    margin-bottom: 20px;
}



</style>


<div class="signup-form">
  <form method="POST" enctype="multipart/form-data">
      {{form.hidden_tag()}}
      <img class="mb-4" src="static/images/{{user.get('picture')}}" alt="" width="72" height="57">
      <h4 class="text-muted">Account for {{user.get('username')}}</h4>
      <p></p>
      <div  class="mb-3" align="center">
          {{form.email(class="form-control border-0", placeholder="Email")}}
          <br>
          {{form.username(class="form-control border-0",  placeholder="Username")}}
          <br>
          {{form.password(class="form-control border-0", placeholder="Password")}}
          <br>
          {{form.picture(class="form-control custom-file-upload")}}
          <br>
          {{form.update(class="btn btn-success", style="width: 10rem; height:3rem; font-size: 20px; font-weight: bold;")}}
          {{form.delete(class="btn btn-danger", style="width: 10rem; height:3rem; font-size: 20px; font-weight: bold;")}}

      </div>

  </form>
</div>

{% endblock %}

microservices_chatbot/frontend/templates/base.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>PyChat</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/cover/">>


    <!-- Bootstrap core CSS -->
      <link href="static/home/bootstrap.min.css" rel="stylesheet">
      <link href="static/home/cover.css" rel="stylesheet">


  </head>
      <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  <body class="d-flex h-100  bg-dark">
  <div class="cover-container text-center d-flex w-100 h-100 p-3 mx-auto flex-column">
            <header class="mb-auto">
                <div>
                    <div class="float-md-start mb-0">
                        <img src="static/images/original.png">
                    </div>
                    <nav class="nav nav-masthead justify-content-center float-md-end">
                    {% if not current_user.is_authenticated %}
                        {% if page=="home" %}
                        <a class="nav-link active" aria-current="page" href="{{ url_for('core.home') }}">Home</a>
                        <a class="nav-link" href="{{ url_for('core.login') }}">Login</a>
                        <a class="nav-link" href="{{ url_for('core.register') }}">Register</a>

                        {% elif page=="login" %}
                        <a class="nav-link" href="{{ url_for('core.home') }}">Home</a>
                        <a class="nav-link active" aria-current="page" href="{{ url_for('core.login') }}">Login</a>
                        <a class="nav-link" href="{{ url_for('core.register') }}">Register</a>

                        {% elif page=="register" %}
                        <a class="nav-link" href="{{ url_for('core.home') }}">Home</a>
                        <a class="nav-link" href="{{ url_for('core.login') }}">Login</a>
                        <a class="nav-link active" aria-current="page" href="{{ url_for('core.register') }}">Register</a>
                        {% endif %}
                     {% else %}
                         {% if page=="home" %}
                         <a class="nav-link active" aria-current="page" href="#">Home</a>
                         <a class="nav-link" href="{{ url_for('chats.chat') }}">Chat</a>
                         <a class="nav-link" href="{{ url_for('core.account') }}">Account</a>
                         <a class="nav-link" href="{{ url_for('core.logout') }}">Logout</a>

                         {% elif page=="chat"%}
                        <a class="nav-link" href="{{ url_for('core.home') }}">Home</a>
                        <a class="nav-link active" href="#">Chat</a>
                        <a class="nav-link" href="{{ url_for('core.account') }}">Account</a>
                        <a class="nav-link" href="{{ url_for('core.logout') }}">Logout</a>

                        {% elif page=="account" %}
                        <a class="nav-link" href="{{ url_for('core.home') }}">Home</a>
                        <a class="nav-link" href="{{ url_for('chats.chat') }}">Chat</a>
                        <a class="nav-link active" href="#">Account</a>
                        <a class="nav-link" href="{{ url_for('core.logout') }}">Logout</a>
                        {% endif %}
                    {% endif %}
                    <!--- ENDIF --->
                    </nav>
                 </div>
             </header>

              <main class="px-3">
                  {% block content %}

                  {% endblock %}
              </main>

          <footer class="mt-auto text-white-50">
            <!---
            <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
            --->
            <p class="mt-5 mb-3 text-muted"><a href="{{ url_for('measurements.stats') }}" class="text-white" style="font-weight: bold; text-decoration:none;">Endpoint</a> measurements. &copy; 2021–2022</p>
          </footer>
        </div>
    </body>
</html>

microservices_chatbot/frontend/templates/chat.html
{% extends "base.html" %}
{% block content %}
<!------>

  <style>

      .form-control {
          color: gray;
          padding: 0;
          font-size: 16px;

      }
      .small {
          color: gray;
          padding: 0;
          font-size: 14px;

      }
      .card-header a.nav-link {
          color: gray;
          padding: 0;
          font-size: 22px;
      }
      .card .card-text {
          color: gray;
          padding: 0;
          font-size: 16px;
          border: 2px solid light-gray;
          border-radius: 8px;
      }
      .avatar {
        width: 50px;
        height: 50px;
        border-radius: 50%;
        border: 2px solo #e84118;
        padding: 2px;
      }

      input:focus {
          outline: 0px !important;
          box-shadow: none !important;
      }

      .card-text {

      }
  </style>

  <body>
    <form method="POST">
      {{form.hidden_tag()}}
        <div class="container mt-4">
            <div class="card mx-auto" style="max-width: 300;">
                <!--HEADER-->
                <div class="card-header bg-transparent">
                    <div class="navbar navbar-expand p-0">

                        <ul class="navbar-nav me-auto align-items-center">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <div class="position-relative" style="width: 50px; height: 50px; border-radius: 50%; border: 2px solo #e84118; padding: 2px;">
                                        <img src="static/images/{{user.get('picture')}}" class="img-fluid rounded-circle">

                                        <span class="position-absolute bottom-0 start-100 translate-middle p-1 bg-success border border-light rounded-circle">
                                            <span class="visually-hidden">New alerts</span>
                                        </span>
                                    </div>

                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">{{user.get('username')}}</a>
                            </li>
                        </ul>

                        <ul class="navbar-nav ms-auto">
                            </li>
                            <li class="nav-item">
                                <a href="{{url_for('chats.reset')}}" class="nav-link">
                                    <img src="static/images/reboot.svg">
                                </a>
                            </li>
                        </ul>

                    </div>

                </div>

                <!--BODY-->
                <div class="card-body p-4" style="height: 500px; overflow: auto;">

                    {% for chat in data %}

                    <!--- REQUEST WITH IMAGE --->
                    <div class="d-flex align-items-baseline mb-4">
                        <!--- IMAGE RIGHT --->
                        <div class="position-relative avatar">
                            <img src="static/images/{{user.get('picture')}}" class="img-fluid rounded-circle">

                            <span class="position-absolute bottom-0 start-100 translate-middle p-1 bg-success border border-light rounded-circle">
                                <span class="visually-hidden">New alerts</span>
                            </span>
                        </div>
                        <!--- TEXT --->
                        <div class="pe-2">
                            <div>
                                <div class="card card-text d-inline-block p-2 px-3 m-1">
                                    {{chat.get('input')}}
                                </div>
                            </div>
                            <!--DATE-->
                            <div>
                                <div class="small">
                                    {{chat.get('input_date')}}
                                </div>
                            </div>
                            <!----->
                        </div>
                    </div>

                    <!---RESPONSE WITH IMAGE-->
                    <div class="d-flex align-items-baseline mb-4">
                        <!--OUTPUT TEXT-->
                        <div class="pe-2">
                            <div>
                                <div class="card card-text d-inline-block p-2 px-3 m-1">
                                    {{chat.get('output')}}
                                </div>
                            </div>
                                                        <!--DATE-->
                            <div>
                                <div class="small">
                                    {{chat.get('output_date')}}
                                </div>
                            </div>
                            <!----->
                        </div>

                        <!---IMAGE LEFT--->
                        <div class="position-relative avatar">
                            <img src="static/images/ai.png" class="img-fluid rounded-circle">
                            <span class="position-absolute bottom-0 start-100 translate-middle p-1 bg-success border border-light rounded-circle">
                                <span class="visually-hidden">New alerts</span>
                            </span>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!--- END OF BODY --->

                <!--FOOTER-->
                <div class="card-footer bg-transparent position-absolute w-100 bottom-0 m-0 p-1">
                    <div class="input-group">
                        {{form.text(class="form-control border-0", placeholder="Write a message...", style="font-size: 18px; margin-left: 15px;")}}
                        <div class="input-group-text bg-transparent border-0" >
                            {{form.send(class="btn btn-light text-secondary", style="font-size: 20px;")}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </form>
  </body>


{% endblock %}

microservices_chatbot/frontend/templates/history.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Dashboard Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



    <!-- Bootstrap core CSS -->
<link href="static/home/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="static/stats/dashboard.css" rel="stylesheet">
  </head>
  <body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <!---
  <a class="nav-link px-3" href="#">Sign out</a>
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{{ url_for('core.home') }}">Home</a>
  --->
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Stats</a>

</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ url_for('core.home') }}">
              <span data-feather="home"></span>
              Home
            </a>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{url_for('measurements.stats')}}">
              <span data-feather="bar-chart-2"></span>
              Logs
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="#">
              <span data-feather="file"></span>
              History
            </a>

        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <h2>History</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">User text</th>
              <th scope="col">User date</th>
              <th scope="col">Ai text</th>
              <th scope="col">Ai date</th>
            </tr>
          </thead>
          <tbody>
          {% for post in posts %}
            <tr>
              <td>{{post.get('id')}}</td>
              <td>{{post.get('user_text')}}</td>
              <td>{{post.get('user_date')}}</td>
              <td>{{post.get('ai_text')}}</td>
              <td>{{post.get('ai_date')}}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


    <script src="static/stats/bootstrap.bundle.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="static/stats/dashboard.js"></script>
  </body>
</html>

microservices_chatbot/frontend/templates/stats.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Dashboard Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
<link href="static/home/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="static/stats/dashboard.css" rel="stylesheet">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <!---
  <a class="nav-link px-3" href="#">Sign out</a>
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{{ url_for('core.home') }}">Home</a>
  --->
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Stats</a>

</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ url_for('core.home') }}">
              <span data-feather="home"></span>
              Home
            </a>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="bar-chart-2"></span>
              Logs
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('measurements.history') }}">
              <span data-feather="file"></span>
              History
            </a>

        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <h2>Logs</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Tag</th>
              <th scope="col">Endpoint name</th>
              <th scope="col">Took (ms)</th>
              <th scope="col">Date</th>
              <th scope="col">Min | Max | Mean (ms)</th>
            </tr>
          </thead>
          <tbody>
          {% for log in logs %}
            <tr>
              <td>{{log.get('tag')}}</td>
              <td>{{log.get('name')}}</td>
              <td>{{log.get('took')}}</td>
              <td>{{log.get('date')}}</td>
              <td>{{log.get('mean')}}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


    <script src="static/stats/bootstrap.bundle.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="static/stats/dashboard.js"></script>
  </body>
</html>