microservices_jobs/frontend/api/jobs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField


class CreateJobForm(FlaskForm):
    title = StringField("Title: ")
    description = TextAreaField("Description: ")
    submit = SubmitField("Submit")


class CreateCompanyForm(FlaskForm):
    name = StringField("Name: ")
    description = TextAreaField("Description: ")
    submit = SubmitField("Submit")

microservices_jobs/frontend/api/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from flask_wtf.file import FileAllowed, FileRequired, FileField


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Log In")


class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), EqualTo("pass_confirm", message="Must match")])
    pass_confirm = PasswordField("Confirm Password", validators=[DataRequired()])
    submit = SubmitField("Register")


class UpdateUserForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[Email(), DataRequired()])
    picture = FileField("Update profile picture", validators=[FileAllowed(["jpg", "png", "jpeg"])])
    submit = SubmitField("Update")

microservices_jobs/frontend/__init__.py
from flask import Flask, render_template
from flask_login import LoginManager

from frontend.api.users.views import User
from frontend.config import BaseConfig

app = Flask(__name__)
app.config.from_object(BaseConfig)

login_manager = LoginManager()
login_manager.init_app(app)


@login_manager.user_loader
def user_loader(username):
    user = User()
    user.id = username
    return user


@login_manager.unauthorized_handler
def unauthorized():
    return render_template("401.html")

from frontend.api.core.views import core
from frontend.api.users.views import users
from frontend.api.jobs.views import jobs

app.register_blueprint(core)
app.register_blueprint(users)
app.register_blueprint(jobs)

microservices_jobs/frontend/api/__init__.py
import os

# Url for all endpoints:
url_for_jobs = "http://jobs-service-c:5001/graphql" \
    if os.environ.get("DOCKER") else "http://127.0.0.1:5001/graphql"

url_for_users = "http://users-service-c:5002" \
    if os.environ.get("DOCKER") else "http://127.0.0.1:5002"

# Headers:
headers = {'accept': 'application/json'}
content_headers = {'accept': 'application/json', 'Content-Type': 'application/json'}

microservices_jobs/frontend/api/core/views.py
from flask import Blueprint, render_template
from flask_login import current_user

core = Blueprint("core", __name__)


@core.route("/")
def index():
    return render_template("index.html", current_user=current_user)

microservices_jobs/frontend/api/jobs/views.py
import requests
from flask import Blueprint, render_template, redirect, url_for, session
from flask_login import login_required, current_user

from frontend.api import url_for_jobs, content_headers
from frontend.api.jobs.forms import CreateJobForm, CreateCompanyForm
from frontend.api.jobs.commands import (
    QUERY_COMPANY_BY_ID,
    QUERY_JOB_BY_ID,
    MUTATION_CREATE_JOB,
    QUERY_ALL_JOBS,
    MUTATION_CREATE_COMPANY,
)


jobs = Blueprint("jobs", __name__)


def post_request(query, id=None):
    return requests.request(
        method="POST",
        url=url_for_jobs,
        json={'query': query, "variables": {"id": id}},
        headers=content_headers
    )


def post_mutation(query, input):
    return requests.request(
        method="POST",
        url=url_for_jobs,
        json={'query': query, "variables": {"input": input}},
        headers=content_headers
    )


@jobs.route("/jobs")
@login_required
def get_all_jobs():
    return render_template(
        "index.html",
        current_user=current_user,
        jobs=post_request(QUERY_ALL_JOBS).json()["data"]["jobs"]
    )


@jobs.route("/jobs/<id>", methods=["POST", "GET"])
@login_required
def get_job_id(id):
    return render_template(
        "job.html",
        job=post_request(QUERY_JOB_BY_ID, id).json()["data"]["job"]
    )


@jobs.route("/companies/<company_id>", methods=["POST", "GET"])
@login_required
def get_company_id(company_id):
    return render_template(
        "company.html",
        company=post_request(QUERY_COMPANY_BY_ID, company_id).json()["data"]["company"]
    )


@jobs.route("/create", methods=["POST", "GET"])
@login_required
def create_job():
    company = post_request(QUERY_COMPANY_BY_ID, current_user.id).json()["data"]["company"]
    if company:
        form = CreateJobForm()
        if form.validate_on_submit():
            response = post_mutation(
                query=MUTATION_CREATE_JOB,
                input={
                    "companyId": current_user.id,
                    "title": form.data.get("title"),
                    "description": form.data.get("description")
                }
            )
            return redirect(url_for("jobs.get_all_jobs"))
        return render_template("create_job.html", form=form)

    return redirect(url_for("jobs.create_company"))


@jobs.route("/company", methods=["POST", "GET"])
def create_company():
    form = CreateCompanyForm()
    if form.validate_on_submit():
        response = post_mutation(
            query=MUTATION_CREATE_COMPANY,
            input={
                "id": current_user.id,
                "name": form.data.get("name"),
                "description": form.data.get("description")
            }
        )
        return redirect(url_for("jobs.create_job"))
    return render_template("create_company.html", form=form)


@jobs.app_errorhandler(404)
def error404(_):
    return {}, 404

microservices_jobs/frontend/api/users/views.py
import os

import requests
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, UserMixin, logout_user, \
    login_required, current_user

from frontend.api import url_for_users, content_headers
from frontend.api.users.forms import RegistrationForm, LoginForm

users = Blueprint("users", __name__)


class User(UserMixin):
    def __repr__(self):
        return f"<User {self.__dict__}"


@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        data = {"email": form.email.data, "username": form.username.data, "password": form.password.data}
        response = requests.request("POST", url=f"{url_for_users}/user", json=data, headers=content_headers)
        if response.status_code == 200:
            flash("Thanks for registration!")
            return redirect(url_for("users.login"))

    return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        data = {"email": form.email.data,  "password": form.password.data}
        response = requests.request("POST", url=f"{url_for_users}/check", json=data, headers=content_headers)
        if response.status_code == 200:
            user = response.json()

            user_login = User()
            user_login.id = user["user_id"]
            user_login.username = user["username"]
            user_login.email = user["email"]
            user_login.password = user["password"]

            login_user(user_login)
            flash("Log in Success.")

            return redirect(url_for("jobs.get_all_jobs"))

        elif response.status_code == 500:
            flash(response.json().get("error"))
        elif response.status_code == 404:
            flash(message="You are not registered.")
            return render_template("login.html", form=form), 200

    return render_template("login.html", form=form), 200


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("core.index"))

microservices_jobs/frontend/templates/401.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>401</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="static/401.css">
    <!------ Include the above in your HEAD tag ---------->

</head>


<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>
                    401 Unauthorized access !</h2>
                <div class="error-details">
                    Sorry, an error has occurred, you are not logged in!
                </div>
                <div class="error-actions">
                    <a href="{{url_for('core.index')}}" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                        Take Me Home </a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

microservices_jobs/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Frontend App</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="static/base.css">

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container-fluid">
          {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="{{ url_for('jobs.get_all_jobs') }}">Home</a>
          {% else %}
          <a class="navbar-brand" href="{{ url_for('core.index') }}">Home</a>
          {% endif %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
              {% if not current_user.is_authenticated %}
                  <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                  </li>
                  <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('jobs.create_job') }}">Post</a>
                  </li>
                  <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                  </li>
              {% endif %}

          </ul>
        </div>
      </div>
    </nav>
    <p></p>
    {% block content %}

    {% endblock %}

</body>
</html>

microservices_jobs/frontend/templates/company.html
{% extends "base.html" %}
{% block content %}

<div class="container" style="width: 50rem;">
    <div class="container">
        <h3>{{company['name'].capitalize()}}</h3>
        <div class="list-group">
              <label class="list-group-item d-flex gap-3">
                <span class="pt-1 form-checked-content">
                    {{company["description"].capitalize()}}
                </span>
              </label>
        </div>
        <p>
        <h5>Jobs at {{company["name"].capitalize()}}</h5>
        </p>
        <div class="container">
            <div class="bg-light p-3 rounded" align="center">
                <div class="list-group">
                    {% for job in company["jobs"] %}
                    <label class="list-group-item d-flex gap-3">
                        <span class="pt-1 form-checked-content">
                            {{job["title"].capitalize()}}
                        </span>
                    </label>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

microservices_jobs/frontend/templates/create_company.html
{% extends "base.html" %}
{% block content %}

<main class="container">
  <div class="bg-light p-3 rounded" align="center">
    <h3>Create Company</h3>
    <p>Add Company first.</p>
  </div>
<div class="container">
  <form method="POST">
      {{form.hidden_tag()}}
      <p></p>
      <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
          <span>
          {{form.name.label(class="form-label")}}
          {{form.name(class="form-control")}}
          </span>
          <br>
          <span>
          {{form.description.label(class="form-label")}}
          {{form.description(class="form-control", rows=3, type="text")}}
          </span>

      </div>
      {{form.submit(class="btn btn-primary")}}
  </form>
</div>
</main>
{% endblock %}

microservices_jobs/frontend/templates/create_job.html
{% extends "base.html" %}
{% block content %}

<main class="container">
  <div class="bg-light p-3 rounded" align="center">
    <h3>New Job</h3>
    <p>Create new job.</p>
  </div>
<div class="container">
  <form method="POST">
      {{form.hidden_tag()}}
      <p></p>
      <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
          <span>
          {{form.title.label(class="form-label")}}
          {{form.title(class="form-control")}}
          </span>
          <br>
          <span>
          {{form.description.label(class="form-label")}}
          {{form.description(class="form-control", rows=3, type="text")}}
          </span>

      </div>
      {{form.submit(class="btn btn-primary")}}
  </form>
</div>
</main>
{% endblock %}

microservices_jobs/frontend/templates/index.html
{% extends "base.html" %}
{% block content %}

{% if current_user.is_authenticated %}
<div class="container" style="width: 50rem;">
    <div class="container">
        <h2>Job Board</h2>
        <p></p>
        <div class="list-group">
            {% for job in jobs %}
              <label class="list-group-item d-flex gap-3">
                <span class="pt-1 form-checked-content">
                  <a href="{{ url_for('jobs.get_job_id', id=job['id']) }}">JOB at {{job["company"]["name"]}}:</a> 
                      <p>{{job['id']}} </p>
                </span>
              </label>
            {% endfor %}
        </div>
    </div>
</div>

{% else %}
<main class="container">
  <div class="jumbotron" align="center" style="background-color: #e2e2e2;">
    <h3>Jobs Manager</h3>
    <p>First you need to register.</p>
  </div>


</main>

<div class="to-bottom">
    <div class="b-example-divider"></div>
<footer>
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">&copy; 2021 Company, Inc</p>
</footer>
</div>
{% endif %}
{% endblock %}

microservices_jobs/frontend/templates/job.html
{% extends "base.html" %}
{% block content %}

<div class="container" style="width: 50rem;">
    <div class="container">
        <h3>{{job['title'].capitalize()}}</h3>
        <a href="{{ url_for('jobs.get_company_id', company_id=job['companyId']) }}">{{job['company']['name'].capitalize()}}</a>
        <div class="list-group">
              <label class="list-group-item d-flex gap-3">
                <span class="pt-1 form-checked-content">
                    {{job["description"].capitalize()}}
                </span>
              </label>
        </div>
    </div>
</div>
{% endblock %}

microservices_jobs/frontend/templates/login.html
{% extends "base.html" %}
{% block content %}

<main class="container">
  <div class="bg-light p-3 rounded" align="center">
    <h3>Log In</h3>
    <p>Example help.</p>
  </div>

  <form method="POST">
      {{form.hidden_tag()}}


          <div class="mb-3">
              {{form.email.label(class="form-label")}}
              {{form.email(class="form-control")}}
              <div class="form-text">Enter email.</div>
              <br>
              {{form.password.label(class="form-label")}}
              {{form.password(class="form-control")}}
              <div class="form-text">Enter password.</div>
          </div>


      {{form.submit(class="btn btn-primary")}}

  </form>
</main>
{% endblock %}

microservices_jobs/frontend/templates/register.html
{% extends "base.html" %}
{% block content %}

<main class="container">
  <div class="bg-light p-3 rounded" align="center">
    <h3>Register</h3>
    <p>Example help.</p>
  </div>


  <form method="POST">

      {{form.hidden_tag()}}

          <div class="mb-3">
              {{form.email.label(class="form-label")}}
              {{form.email(class="form-control")}}
              <div class="form-text">Enter email.</div>
          </div>

          <div class="mb-3">
              {{form.username.label(class="form-label")}}
              {{form.username(class="form-control")}}
              <div class="form-text">Enter username.</div>
          </div>

          <div class="mb-3">
              {{form.password.label(class="form-label")}}
              {{form.password(class="form-control")}}
              <div class="form-text">Enter password.</div>
          </div>

          <div class="mb-3">
              {{form.pass_confirm.label(class="form-label")}}
              {{form.pass_confirm(class="form-control")}}
              <div class="form-text">Enter password.</div>
          </div>

          {{form.submit(class="btn btn-primary")}}

  </form>
</main>
{% endblock %}