microservices_emotions/frontend/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    submit = SubmitField("Post")


class UpdateBlogPostForm(FlaskForm):
    id = IntegerField()
    title = StringField("Title", validators=[], render_kw={"placeholder": "Title"})
    text = TextAreaField("Text", validators=[], render_kw={"placeholder": "Text"})
    update = SubmitField("Update")
    delete = SubmitField("Delete")

microservices_emotions/frontend/core/views.py
from quart import Blueprint, render_template
from flask_login import current_user

core = Blueprint("core", __name__)


@core.route("/")
async def index():
    return await render_template("index.html", current_user=current_user)

microservices_emotions/frontend/posts/__init__.py
from .views import posts

microservices_emotions/frontend/posts/views.py
import os
import ast
import datetime

import json
import requests
from quart import Blueprint, render_template, request
from quart import flash, redirect, url_for
from flask_login import login_user, UserMixin, logout_user, \
    login_required, current_user
from werkzeug.utils import secure_filename

from .forms import BlogPostForm, UpdateBlogPostForm

posts = Blueprint("posts", __name__)
url = "http://posts-service-c:5001/" if os.environ.get("DOCKER") else "http://127.0.0.1:5001"


@posts.route("/create", methods=["POST", "GET"])
@login_required
async def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        data = {"username": current_user.id, "title": form.title.data, "text": form.text.data}
        headers = {'accept': 'application/json', 'Content-Type': 'application/json'}

        blog_post = requests.request("POST", url=f"{url}/post/create", json=data, headers=headers)

        user = requests.request("GET", url=f"{url}/user/{current_user.id}", headers={'accept': 'application/json'})

        response = requests.request("GET", url=f"{url}/post/{current_user.id}", headers={'accept': 'application/json'})
        blog_posts = response.json()

        return await render_template("posts.html", user=user.json(), blog_posts=blog_posts.get('posts'))

    response = requests.request("GET", url=f"{url}/user/{current_user.id}", headers={'accept': 'application/json'})
    return await render_template("post.html", form=form, user=response.json())


@posts.route("/update", methods=["POST", "GET"])
@login_required
async def update_post():
    """Update or delete post by post id"""
    post, user = request.args.get("post"), request.args.get("user")
    post, user = ast.literal_eval(post), ast.literal_eval(user)

    form = UpdateBlogPostForm()
    form.id.data = post.get("id")
    form.id.label = f"id: {post.get('id')}"
    form.title.render_kw["placeholder"] = post.get("title")
    form.text.render_kw["placeholder"] = post.get("text")
    if request.method == "POST":
        response = await request.form
        # FOR UPDATE POST
        if response.get("update"):
            if form.id.data and form.title.data:
                data = {"id": form.id.data, "title": form.title.data, "text": form.text.data}
                headers = {'accept': 'application/json', 'Content-Type': 'application/json'}
                response = requests.request("PUT", url=f"{url}/post/update", json=data, headers=headers)
        # FOR DELETE POST
        elif response.get("delete"):
            data = {"id": form.id.data}
            headers = {'accept': 'application/json', 'Content-Type': 'application/json'}
            response = requests.request("DELETE", url=f"{url}/post/delete", json=data, headers=headers)
            if response.status_code == 204:
                await flash("Deleted")
        else:
            raise NotImplemented("Not implemented yet.")

        response = requests.request("GET", url=f"{url}/post/{current_user.id}", headers={'accept': 'application/json'})
        blog_posts = response.json()
        return await render_template("posts.html", user=user, blog_posts=blog_posts.get('posts'))

    return await render_template("update.html", form=form, user=user)


@posts.route("/all")
@login_required
async def get_all_posts():
    username = current_user.id
    user = requests.request("GET", url=f"{url}/user/{username}", headers={'accept': 'application/json'})
    response = requests.request("GET", url=f"{url}/post/{current_user.id}", headers={'accept': 'application/json'})
    blog_posts = response.json().get("posts")
    blog_posts_date = []
    for post in blog_posts:
        date = datetime.datetime.fromisoformat(post["date"]).strftime("%b %d %Y %I:%M%p")
        post["date"] = date
        blog_posts_date.append(post)

    return await render_template("posts.html", user=user.json(), blog_posts=blog_posts_date)

microservices_emotions/frontend/users/views.py
import os
from random import randint
import requests
from PIL import Image
from quart import Blueprint, render_template, request
from quart import flash, redirect, url_for
from flask_login import login_user, UserMixin, logout_user, \
    login_required, current_user
from werkzeug.utils import secure_filename

from .forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint("users", __name__)
url = "http://posts-service-c:5001/" if os.environ.get("DOCKER") else "http://127.0.0.1:5001"


class User(UserMixin):
    pass


@users.route("/register", methods=["GET", "POST"])
async def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        data = {"email": form.email.data, "username": form.username.data, "password": form.password.data}
        headers = {'accept': 'application/json', 'Content-Type': 'application/json'}

        response = requests.request("POST", url=f"{url}/create", json=data, headers=headers)

        if response.status_code == 200:
            await flash("Thanks for registration!")
            return redirect(url_for("users.login"))
        elif response.status_code == 500:
            await flash("Email or username already registered!")
        else:
            raise NotImplemented(f"For {response.status_code}")
    return await render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
async def login():
    form = LoginForm()

    if form.validate_on_submit():
        data = {"email": form.email.data,  "password": form.password.data}
        headers = {'accept': 'application/json', 'Content-Type': 'application/json'}
        response = requests.request("POST", url=f"{url}/user", json=data, headers=headers)
        if response.status_code == 200:
            user = User()
            user.id = response.json().get("username")
            login_user(user)

            await flash("Log in Success.")

            n = request.args.get("next")
            if not n or not n[0] == "/":
                n = url_for("core.index")
            return redirect(n)

        elif response.status_code == 500:
            await flash(response.json().get("error"))
        else:
            raise NotImplemented(f"For {response.status_code}")

    return await render_template("login.html", form=form), 200


@users.route("/logout")
async def logout():
    logout_user()
    return redirect(url_for("core.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
async def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        # OBTAIN PICTURE FROM FORM AND SAVE IT.
        f = form.picture.data
        try:
            filename = secure_filename(f.filename)
            base = os.path.abspath(os.path.dirname(__name__))
            folder = os.path.join(base, "frontend", "static", "images")
            os.makedirs(folder, exist_ok=True)
            path = os.path.join(folder, filename)
            await f.save(path)
            # DELETE OLD, THUMBNAIL, RENAME AND SAVE.
            picture = Image.open(path)
            os.remove(path)
            picture.thumbnail((100, 100))
            i = randint(0, 100)
            picture_name = f"{current_user.id}_{i}.png"
            picture_path = os.path.join(folder, picture_name)
            [os.remove(f"{folder}/{i}") for i in os.listdir(folder) if i.startswith(current_user.id)]
            picture.save(picture_path)
        except AttributeError:
            picture_name = None

        response = requests.request("GET", url=f"{url}/user/{current_user.id}", headers={'accept': 'application/json'})
        user = response.json()

        data = {
            "username": current_user.id,
            "new_username": form.username.data,
            "new_email": form.email.data,
            "new_picture": picture_name if picture_name else user.get("profile_image")
        }

        headers = {'accept': 'application/json', 'Content-Type': 'application/json'}
        response = requests.request("PUT", url=f"{url}/update", json=data, headers=headers)

        # IF USERNAME OR PASSWORD ARE CHANGED LOGOUT
        if form.username.data != user.get("username") or form.email.data != user.get("email"):
            logout_user()
            return redirect(url_for("core.index"))

        return await render_template("account.html", form=form, user=response.json())

    response = requests.request("GET", url=f"{url}/user/{current_user.id}", headers={'accept': 'application/json'})
    return await render_template("account.html", form=form, user=response.json())


@users.route("/<username>")
async def user_posts(username):
    user = requests.request("GET", url=f"{url}/user/{username}", headers={'accept': 'application/json'})
    response = requests.request("GET", url=f"{url}/post/{current_user.id}", headers={'accept': 'application/json'})
    blog_posts = response.json()
    return await render_template("posts.html", user=user.json(), blog_posts=blog_posts.get('posts'))

microservices_emotions/frontend/templates/account.html
{% extends "base.html" %}
{% block content %}
 <div class="container">
  <div class="jumbotron">
      <div align="center">
          <h1>Account for {{user['username']}}</h1>
          <img align="center" src="static/images/{{user['profile_image']}}" alt="">
      </div>
  </div>

      <form method="POST" enctype="multipart/form-data">
          {{form.hidden_tag()}}

              <div class="mb-3">
                  {{form.username.label(class="form-label")}}
                  {{form.username(class="form-control")}}
                  <div class="form-text">Enter old or new to change.</div>
              </div>

              <div class="mb-3">
                  {{form.email.label(class="form-label")}}
                  {{form.email(class="form-control")}}
                  <div class="form-text">Enter old or new to change.</div>
              </div>

              <div class="mb-3">
                  {{form.picture.label(class="form-label")}}
                  {{form.picture(class="form-control")}}

              </div>


              <p></p>
              {{form.submit(class="btn btn-primary")}}





      </form>
  </div>
{% endblock %}

microservices_emotions/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ai Blog</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="static/base.css">

</head>
<body>
    <!--NAVBAR-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('core.index') }}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
          <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
          <a class="nav-item nav-link" href="{{ url_for('posts.create_post') }}">Create Post</a>
          <a class="nav-item nav-link" href="{{ url_for('posts.get_all_posts') }}">All Posts</a>

          {% else %}
          <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Log In</a>
          <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>

    <!---->
<p></p>
    {% block content %}

    {% endblock %}


</body>
</html>

microservices_emotions/frontend/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div align="center">
            <h1>Home Page.</h1>
            {% if current_user.is_authenticated %}
            <p></p>
            <h3>Hello {{current_user.id}}!</h3>
            {% endif %}
        </div>
    </div>
</div>


<div class="container" align="center">
    <img src="static/images/blog.png">
</div>


<div class="container">
<footer class="bg-light text-center text-lg-start" id="footer">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
        <p>
        List the top bloggers in your niche who inspire you with their work.
        Put together a list of underrepresented people in your industry.
        Share a list of things or activities that put you in a good mood.
        Write about how to balance work and family life.
        Talk about the best goal setting planners.
        </p>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
</div>

{% endblock %}

microservices_emotions/frontend/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron" align="center">
      <h1>Log In</h1>
  </div>

  <form method="POST">
      {{form.hidden_tag()}}

      <div class="mb-3">
          {{form.email.label(class="form-label")}}
          {{form.email(class="form-control")}}
          <div class="form-text">Enter email.</div>
          <br>
          {{form.password.label(class="form-label")}}
          {{form.password(class="form-control")}}
          <div class="form-text">Enter password.</div>
      </div>

      {{form.submit(class="btn btn-primary")}}

  </form>
  </div>
{% endblock %}

microservices_emotions/frontend/templates/post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
      <div align="center">
          <h1>Create post for {{user["username"]}}</h1>
          <img src="static/images/{{user['profile_image']}}">
      </div>
  </div>

  <form method="POST">
      {{form.hidden_tag()}}

      <div class="mb-3">
          {{form.title.label(class="form-label")}}
          {{form.title(class="form-control")}}
          <div class="form-text">Enter a title.</div>
          <br>
          {{form.text.label(class="form-label")}}
          {{form.text(class="form-control")}}
          <div class="form-text">Enter text.</div>
      </div>

      {{form.submit(class="btn btn-primary")}}

  </form>
  </div>
{% endblock %}

microservices_emotions/frontend/templates/posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div align="center">
            <h1>All {{user.username}} posts.</h1>
            <img align="center" src="static/images/{{user.profile_image}}" alt="">
        </div>
    </div>
</div>

<div class="container">
    {% for post in blog_posts %}
        <h3> <a methods="POST" href="{{ url_for('posts.update_post', post=post, user=user) }}">{{post.title}}</a></h3>
        Written By: <a href="{{ url_for('users.account') }}">{{user.username}}</a>
        <p class="text-muted">Publish on: {{post.date}}</p>
        <p></p>
        <p>{{post.text}}</p>
        {% if post.emotion == 'joy' %}
            <h4>🙂</h4>
        {% elif post.emotion == 'sadness' %}
            <h4>😒</h4>
        {% elif post.emotion == 'anger' %}
            <h4>😤</h4>
        {% elif post.emotion == 'surprise' %}
            <h4>😏</h4>
        {% elif post.emotion == 'fear' %}
            <h4>😨</h4>
        {% elif post.emotion == 'love' %}
            <h4>😍</h4>
        {% else %}
            <h4>😯</h4>
        {%endif%}
        <p></p>
        {% endfor %}
</div>

    {% endblock %}

microservices_emotions/frontend/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron" align="center">
      <h1>Register</h1>
  </div>
  <form method="POST">

      {{form.hidden_tag()}}

          <div class="mb-3">
              {{form.email.label(class="form-label")}}
              {{form.email(class="form-control")}}
              <div class="form-text">Enter email.</div>
          </div>

          <div class="mb-3">
              {{form.username.label(class="form-label")}}
              {{form.username(class="form-control")}}
              <div class="form-text">Enter username.</div>
          </div>

          <div class="mb-3">
              {{form.password.label(class="form-label")}}
              {{form.password(class="form-control")}}
              <div class="form-text">Enter password.</div>
          </div>

          <div class="mb-3">
              {{form.pass_confirm.label(class="form-label")}}
              {{form.pass_confirm(class="form-control")}}
              <div class="form-text">Enter password.</div>
          </div>

          {{form.submit(class="btn btn-primary")}}

  </form>
</div>

{% endblock %}

microservices_emotions/frontend/templates/update.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
      <div align="center">
          <h1>Update post {{form.id.label}} user: {{user["username"]}}</h1>
          <img src="static/images/{{user['profile_image']}}">
      </div>
  </div>

  <form method="POST">
      {{form.hidden_tag()}}

      <div class="mb-3">
          {{form.title.label(class="form-label")}}
          {{form.title(class="form-control")}}
          <div class="form-text">Enter a title.</div>
          <br>
          {{form.text.label(class="form-label")}}
          {{form.text(class="form-control")}}
          <div class="form-text">Enter text.</div>
      </div>

      {{form.update(class="btn btn-success")}}
      {{form.delete(class="btn btn-danger")}}

  </form>
  </div>
{% endblock %}